name: Laravel Pint

on:
  pull_request

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push Changes Back to the Repo
        run: |
          git config user.name "gh-actions"
          git config user.email "gh@robertogallea.com"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push